base_url = "//worldwidetelescope.org/"
title = "AAS WorldWide Telescope"
description = "AAS WorldWide Telescope is a tool for showcasing astronomical data and knowledge."
default_language = "en"
compile_sass = true
highlight_code = true
build_search_index = false

[slugify]
paths = "safe"  # Preserve capitalization

[extra]
google_analytics_id = "UA-107473046-1"
